import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../style/globals.css";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/hooks/Auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CatConnect",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=6"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-custom-gradient  ${inter.className} `}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
